### ISSUE TITLE
Ban bot not working any longer...

### ISSUE THREAD

**Issue by Euther** [mfrankruijter/BanPurchaseBots#1]
Good day,

I have been getting the following error reported in Chatbot... 

![image](https://user-images.githubusercontent.com/17101249/155845767-37dfc710-2fc6-4cf4-b13e-32987c8d2ffe.png)

Is there anything that could be done to address this?

thx
Euther

**Comment by Euther** [comment]
Also, if this helps, here is the list of "Contains" I had setup
[Contains.txt](https://github.com/mfrankruijter/BanPurchaseBots/files/8146763/Contains.txt)
;

**Comment by mfrankruijter** [comment]
Hi there,

Thanks for the report. Has this been happening since an update to streamlabs? Which version are you currently running? I'll try to check why it isn't working this evening.

**Comment by Euther** [comment]
Possibly... Not sure really. I noticed with a few streams ago, when i witnessed that the script did not autoban. Sorry
I am running script version 1.1.0, I am also running Chatbot c1.0.2.64. I did not update yet.

**Comment by Euther** [comment]
I removed all the "contains", saved, then re-added some, and it worked again this weekend.

**Comment by mfrankruijter** [comment]
Alright. Could be that the object was malformed. I'll see if I can implement the lines differently because those settings objects are giving me more headaches..

**Comment by mfrankruijter** [comment]
I just tested (with the latest version of streamlabs 1.0.2.66) this, everything still seems to function as normal. But I still implemented the read from file method. If you want to make use of this new feature you can see the below links.

Release: https://github.com/mfrankruijter/BanPurchaseBots/releases/tag/1.2.0

Installation instructions: https://github.com/mfrankruijter/BanPurchaseBots#installation

Kind regards.

**Comment by Euther** [comment]
Thank you. I will load the new version. If anything wonkie happens, I will follow up.

V/r,
Mike

**Comment by Euther** [comment]
Quick question... regarding the "read from file" option... in the txt file, to use that... new line for each "banned txt", correct?
thanks,
Mike

e.g.
wanna become famous?
buy followers
bigfollows .com
buy followers and viewers on
buy followers, primes

**Comment by mfrankruijter** [comment]
Yes, just create a file at your desired location, add the banned text lines as a new line (like your example) and don't forget to change the configured path to the path on your pc :)

**Comment by Euther** [comment]
Appreciate the new version!!!
