### ISSUE TITLE
Member did not get banned.

### ISSUE THREAD

**Issue by Euther** [mfrankruijter/BanPurchaseBots#2]
Good day, 
Today I have a bot come into my channel, and ended up manually banning the user name.
- I am currently configured as "read from file"

Chat Message: 20:19  lucaswinchesterh : Wanna become famous? Buy followers, primes and viewers on https://t.ly/ou3F
Chatbot Response: 
 20:19  Gorlois_of_Tintagel : lucaswinchesterh --> Ask for permission before posting a link! [Timeout - 10 mins]
 20:19 lucaswinchesterh has been timed out for 10 minutes.
 20:19 gorlois_of_tintagel timed out lucaswinchesterh for 600 seconds. Reason:
My Discord Message: 
 Banned user: "lucaswinchesterh" for message "wanna become famous buy followers primes and viewers on httpstlyou3f"

However, I ended up manually banning the account since I did not see a message in chatbot that the account was banned.
e.g. 20:22 euther banned lucaswinchesterh.

Thank you,
E

**Comment by mfrankruijter** [comment]
Hi there,

Sorry I forgot to uncomment the line where it bans a user. Should be fixed in version 1.2.1 :) 

Kind regards

**Comment by Euther** [comment]
Thanks! I appreciate it!
